# docker-compose.yml
version: '3.8'

services:
  # This new service just builds the base image
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: ai-news-base:latest

  backend:
    # This now depends on the 'base' service being built first
    depends_on:
      - base
    # It uses the image built by the 'base' service
    image: ai-news-base:latest
    # We still need a custom command
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./services:/app/services
    hostname: backend

  frontend:
    depends_on:
      - base
    image: ai-news-base:latest
    command: streamlit run ui/dashboard.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./ui:/app/ui