FROM python:3.11-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy only the requirements file
COPY requirements.txt .

RUN pip install --timeout=600 --no-cache-dir -r requirements.txt